name: TopredStoneTweaks
version: "1.0"
authors: [Nano_, Omeganx, Likyaz]
main: fr.topred.topredstonetweaks.Main
api-version: "1.13"
website: topred.fr
commands:
  f:
    description: TopredStoneTweaks
    usage: Usage /f [0-15]